# Generated by Django 5.0.2 on 2024-02-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0002_cryptodetailsmodel_delete_crptodetailsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptodetailsmodel',
            old_name='cr_id',
            new_name='my_id',
        ),
    ]
