# Generated by Django 5.0.2 on 2024-02-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0003_rename_cr_id_cryptodetailsmodel_my_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptodetailsmodel',
            name='the24h',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cryptodetailsmodel',
            name='the7d',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
