# Generated by Django 5.0.2 on 2024-02-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0004_alter_cryptodetailsmodel_the24h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptodetailsmodel',
            name='the7d',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
