# Generated by Django 5.0.2 on 2024-02-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0006_alter_cryptodetailsmodel_the7d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptodetailsmodel',
            name='the7d',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
        ),
    ]
